from django.urls import path
from django.views.generic.base import TemplateView
from .views import ( index, other_page, by_rubric, BBLoginView, 
            BBLogoutView, profile, ChangeUserInfo, BBPasswordChangeView, 
            RegisterUserView, RegisterDoneView, user_activate, 
            DeleteUserView, UserPasswordResetView, 
            UserPasswordResetDoneView, UserPasswordResetConfirmView,
            UserPasswordResetCompleteView, detail, profile_bb_detail,
            profile_bb_add, profile_bb_change, profile_bb_delete )

app_name = 'main'
urlpatterns = [
    path('accounts/password_reset/', UserPasswordResetView.as_view(), 
            name='password_reset'),
    path('accounts/password_reset/done/', UserPasswordResetDoneView.as_view(),
            name='password_reset_done'),    
    path('accounts/reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(),
            name='password_reset_confirm'),
    path('accounts/reset/done/', UserPasswordResetCompleteView.as_view(),
            name='password_reset_complete'), 
    path('accounts/profile/delete/', DeleteUserView.as_view(), 
            name='profile_delete'),
    path('accounts/register/activate/<str:sign>/', user_activate, 
            name='register_activate'),
    path('accounts/register/done', RegisterDoneView.as_view(), 
            name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), 
            name='register'),
    path('accounts/profile/change/', ChangeUserInfo.as_view(), 
            name='profile_change'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(),
            name='password_change'),
    path('accounts/profile/<int:pk>', profile_bb_detail, 
            name='profile_bb_detail'),
    path('accounts/profile/delete/<int:pk>/', profile_bb_delete, 
            name='profile_bb_delete'),
    path('accounts/profile/change/<int:pk>/', profile_bb_change, 
            name='profile_bb_change'),
    path('accounts/profile/add/', profile_bb_add, name='profile_bb_add'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="main/robots.txt", content_type="text/plain"),
    ),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

